---
- name: Apt install required system packages.
  apt: pkg={{ item }} state=installed
  tags: bootstrap
  with_items:
    - zookeeper
    - zookeeperd

- name: Overwrite myid file.
  template: src=myid.j2 dest=/etc/zookeeper/conf/myid
  tags: deploy

- name: Overwrite default config file
  template: src=zoo.cfg.j2 dest=/etc/zookeeper/conf/zoo.cfg
  notify: Restart zookeeper
  tags: deploy

- name: Start zookeeper
  service: name=zookeeper state=started enabled=yes
  tags: deploy
