---
- name: Apt install required system packages.
  apt: pkg={{ item }} state=installed
  with_items:
    - zookeeper
    - zookeeperd

- name: Setup config for zookeeper
  template: src=zookeeper_conf.j2 dest=/etc/zookeeper/conf/zoo.cfg

- name: Overwrite myid file.
  template: src=myid.j2 dest=/etc/zookeeper/conf/myid

- name: Overwrite default config file
  template: src=zk_conf.j2 dest=/etc/zookeeper/conf/zoo.cfg
  notify: Restart zookeeper

- name: Install master zookeeper adresses
  template: src=zk_master_mesos.j2 dest=/etc/mesos/zk
  when: node

- name: Start zookeeper
  service: name=zookeeper state=started enabled=yes
