# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1536
    v.cpus = 1
  end

  config.vm.define "vm1" do |vm1|
    vm1.vm.hostname = 'vm1'
    vm1.vm.network "private_network", ip: "192.168.33.10"
  end

  config.vm.define "vm2" do |vm2|
    vm2.vm.hostname = 'vm2'
    vm2.vm.network "private_network", ip: "192.168.33.11"
  end

  config.vm.define "vm3" do |vm3|
    vm3.vm.hostname = 'vm3'
    vm3.vm.network "private_network", ip: "192.168.33.12"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/vagrant.yml"
    ansible.sudo = true
  end
end
